## Numpy Questions

### 1) Create a 1D array from a list

In [1]:
import numpy as np

my_list = [10, 20, 30, 40, 50]
array_1d = np.array(my_list)

print("1D NumPy Array:", array_1d)

1D NumPy Array: [10 20 30 40 50]


### 2) Create a 3x3 array of zeros

In [2]:
import numpy as np

zeros_array = np.zeros((3, 3))
print("3x3 Array of Zeros:\n", zeros_array)

3x3 Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 3) Create a 2x2 array of ones

In [3]:
import numpy as np

ones_array = np.ones((2, 2))
print("2x2 Array of Ones:\n", ones_array)

2x2 Array of Ones:
 [[1. 1.]
 [1. 1.]]


### 4) Generate an array from 0 to 10 (exclusive)

In [4]:
import numpy as np

array = np.arange(0, 10)
print("Array from 0 to 9:", array)

Array from 0 to 9: [0 1 2 3 4 5 6 7 8 9]


### 5) Create 5 evenly spaced numbers between 0 and 1

In [5]:
import numpy as np
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


### 6) Create a 4x4 identity matrix

In [6]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 7) Reshape a 1D array to 2D

In [7]:
a = np.arange(6)
reshaped = a.reshape(2, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


### 8) Get the shape and dtype of an array

In [8]:
b = np.array([[1, 2], [3, 4]])
print(b.shape)
print(b.dtype)

(2, 2)
int32


### 9) Reverse a NumPy array

In [9]:
c = np.array([1, 2, 3, 4, 5])
reversed_c = c[::-1]
print(reversed_c)

[5 4 3 2 1]


### 10) Extract even numbers from an array

In [10]:
d = np.array([1, 2, 3, 4, 5, 6])
even = d[d % 2 == 0]
print(even)

[2 4 6]


### 11) Find the max in each row

In [11]:
e = np.array([[1, 5, 3], [7, 2, 6]])
row_max = np.max(e, axis=1)
print(row_max)

[5 7]


### 12) Compute the mean, std, and median of an array

In [16]:
f = np.array([10, 20, 30, 40, 50])
print(np.mean(f))
print(np.std(f))
print(np.median(f))

30.0
14.142135623730951
30.0


### 13) Stack two arrays vertically

In [17]:
g1 = np.array([1, 2])
g2 = np.array([3, 4])
vstacked = np.vstack((g1, g2))
print(vstacked)

[[1 2]
 [3 4]]


### 14) Stack two arrays horizontally

In [18]:
h1 = np.array([[1], [2]])
h2 = np.array([[3], [4]])
hstacked = np.hstack((h1, h2))
print(hstacked)

[[1 3]
 [2 4]]


### 15) Find the unique values and their counts

In [19]:
i = np.array([1, 2, 2, 3, 1, 4])
unique_vals, counts = np.unique(i, return_counts=True)
print(unique_vals)
print(counts)

[1 2 3 4]
[2 2 1 1]


### 16) Replace NaN with column means

In [21]:
j = np.array([[1, np.nan], [3, 4], [5, np.nan]])
col_means = np.nanmean(j, axis=0)
inds = np.where(np.isnan(j))
j[inds] = np.take(col_means, inds[1])
print(j)

[[1. 4.]
 [3. 4.]
 [5. 4.]]


### 17) Get the index of min and max values

In [22]:
k = np.array([10, 20, 5, 8, 30])
print(np.argmin(k))
print(np.argmax(k))

2
4


### 18) Create a 3D array of random integers

In [23]:
arr_3d = np.random.randint(1, 100, size=(2, 3, 4))
print(arr_3d)

[[[94 42 33 55]
  [29  1 57  5]
  [22 39 65  5]]

 [[78 20  2 52]
  [71 41 60 49]
  [13 89  4 60]]]


### 19) Use np.where() to replace values

In [24]:
l = np.array([1, 2, 3, 4, 5])
replaced = np.where(l > 3, 100, l)
print(replaced)

[  1   2   3 100 100]


## Pandas Questions

### 20) Create a Series using a Python list

In [25]:
import pandas as pd

s1 = pd.Series([10, 20, 30, 40])
print(s1)

0    10
1    20
2    30
3    40
dtype: int64


### 21) Create a Series with custom string indices

In [26]:
s2 = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
print(s2)

a    100
b    200
c    300
dtype: int64


### 22) Create a Series from a dictionary

In [27]:
s3 = pd.Series({'Math': 90, 'Science': 85, 'English': 95})
print(s3)

Math       90
Science    85
English    95
dtype: int64


### 23) Access the first 3 elements of a series

In [28]:
print(s1[:3])

0    10
1    20
2    30
dtype: int64


### 24) Filter Series elements greater than 50

In [29]:
s4 = pd.Series([45, 60, 75, 20, 90])
print(s4[s4 > 50])

1    60
2    75
4    90
dtype: int64


### 25) Add two series with different indices

In [30]:
s5 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s6 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])
print(s5 + s6)

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64


### 26) Multiply a Series by a scalar

In [31]:
print(s5 * 10)

a    10
b    20
c    30
dtype: int64


### 27) Use .multiply() method to multiply with a scalar

In [33]:
print(s5.multiply(5))

a     5
b    10
c    15
dtype: int64


### 28) Sort Series by values descending

In [34]:
s7 = pd.Series([15, 40, 5, 25])
print(s7.sort_values(ascending=False))

1    40
3    25
0    15
2     5
dtype: int64


### 29) Sort Series by index

In [35]:
s8 = pd.Series([100, 200, 300], index=['b', 'c', 'a'])
print(s8.sort_index())

a    300
b    100
c    200
dtype: int64


### 30) Check for null values

In [36]:
s9 = pd.Series([10, None, 30, None, 50])
print(s9.isnull())

0    False
1     True
2    False
3     True
4    False
dtype: bool


### 31) Concatenate two Series using concat()

In [1]:
import pandas as pd

s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

concatenated = pd.concat([s1, s2])
print("Concatenated Series using concat():\n", concatenated)

Concatenated Series using concat():
 0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64


### 32) Retrieve the first 5 elements using .head()

In [4]:
s3 = pd.Series(range(10))
print("First 5 elements using head():\n", s3.head())

First 5 elements using head():
 0    0
1    1
2    2
3    3
4    4
dtype: int64


### 33) Retrieve the last 5 elements using .tail()

In [5]:
print("Last 5 elements using tail():\n", s3.tail())

Last 5 elements using tail():
 5    5
6    6
7    7
8    8
9    9
dtype: int64


### 34) Convert Series to DataFrame

In [6]:
df = s1.to_frame(name="Values")
print("Converted Series to DataFrame:\n", df)

Converted Series to DataFrame:
    Values
0       1
1       2
2       3


### 35) Replace NaN with 0

In [7]:
s4 = pd.Series([10, None, 30, None, 50])
filled = s4.fillna(0)
print("Series after replacing NaN with 0:\n", filled)

Series after replacing NaN with 0:
 0    10.0
1     0.0
2    30.0
3     0.0
4    50.0
dtype: float64


### 36)  Drop missing values

In [8]:
dropped = s4.dropna()
print("Series after dropping NaN values:\n", dropped)

Series after dropping NaN values:
 0    10.0
2    30.0
4    50.0
dtype: float64


### 37) Check Series data type

In [9]:
print("Data type of Series:", s4.dtype)

Data type of Series: float64
